pipeline {
   agent any

      stages {
         stage('Build') {
            steps {
               sh """
                  make build
                  cd build
                  cmake ..
                  make -j4
               """
            }
         }
      }
}
